### PR TITLE
Support empty array in read_multi and fetch_multi

### PR DESCRIPTION
**Pull request by andruby**
When switching from a memcached store to a redis store, we noticed a difference in behavior when passing an empty array into read_multi or fetch_multi.

With memcached (dalli gem):
```ruby
> Rails.cache.read_multi([])
=> {}
```

With redis (redis-rails gem):
```ruby
> Rails.cache.read_multi([])
NoMethodError: undefined method `map!' for nil:NilClass
```

This PR adds the same behavior to redis-activesupport and includes tests.

PS: I have [another branch](https://github.com/andruby/redis-activesupport/tree/empty-fetch-multi-4.1.6) that adds this on top of v4.1.5.

### CODE REVIEW

**Comment by tubbo** [comment]
@andruby looks like the build on ruby 2.2 and 2.3 is failing. believe it has to do with line 590 where we do:

```ruby
store.fetch("rabbit", :force => true) # force cache miss
```

This could probably be fixed by just passing a block that no-ops:

```ruby
store.fetch("rabbit", :force => true) {} # force cache miss
```

**Comment by andruby** [comment]
@tubbo I've added the empty block to that line. I'm not sure how the changes in this branch would cause the tests to fail.

**Comment by tubbo** [comment]
thanks @andruby
